• Load and display images into the recyclerView.
OmolaraIdowu/iCart pull request #4
Opened 2023-03-19 19:39 UTC by OmolaraIdowu

• Design the product information screen and add some functionality. • Refactored previous UIs
• Changed some images in the JSON file
• Add internet permission

2023-03-19 21:13 UTC, segunfrancis requested changes
Kindly replace all usage of `Button` with `MaterialButton`. It is easier to customise than the normal `Button`. 
All the image URLs you changed were working before you changed them, check your logcat to know why those images aren't loading.
Also take your time to fix all the existing comments and push when you're done

2023-03-19 21:13 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeAdapter.kt
> +) : RecyclerView.Adapter<HomeAdapter.HomeViewHolder>() {
Please change this to a `ListAdapter` instead of this `RecyclerView.Adapter`. 
Check [here](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) for description 
And [here](https://link.medium.com/vugJ7ttWiyb) for example usage

2023-03-19 21:13 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeFragment.kt
> +    private val mainViewModel: MainViewModel by viewModels {
Why are you adding `MainViewModel` here when we already have `HomeViewModel` above? @OmolaraIdowu

2023-03-19 21:13 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeFragment.kt
> +    private lateinit var recyclerView: RecyclerView
This object instance is used in only one method so it doesn't need to be a global variable. Please make it a local variable @OmolaraIdowu

2023-03-19 21:13 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeViewModel.kt
> +import android.widget.ImageView
Kindly remove unused import statements @OmolaraIdowu

2023-03-19 21:13 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeAdapter.kt
> +            homeItemImageView.load(productItem.imageUrl) {
Kindly create an extension function for the `load` method so it can be reused easily @OmolaraIdowu

2023-03-21 09:27 UTC, segunfrancis requested changes
Try to maintain the same spacing for your layouts and views. The sizes of your views should also be consistent across the app

2023-03-21 09:27 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeFragment.kt
> +        val recyclerView = binding.homeRecyclerView
This assignment isn't required, just call `binding.homeRecyclerView` to reference your RecyclerView

2023-03-21 09:27 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/product/ProductDetailsFragment.kt
>              binding.productDescription.text = it.description
You can extract all these into a method in order to keep the `onViewCreated()` simple

2023-03-21 09:27 UTC, segunfrancis commented on app/src/main/res/layout/fragment_product_details.xml
> +    <androidx.core.widget.NestedScrollView
Do you really need a `NestedScrollView` here? @OmolaraIdowu

2023-03-21 09:27 UTC, segunfrancis commented on app/src/main/res/layout/fragment_product_details.xml
> +            <androidx.cardview.widget.CardView
Kindly replace all usage of `androidx.cardview.widget.CardView` with `MaterialCardView` @OmolaraIdowu

2023-03-21 09:27 UTC, segunfrancis commented on app/src/main/java/com/swancodes/icart/ui/home/HomeAdapter.kt
>          fun bind(productItem: Product, context: Context) = with(binding) {
Instead of passing the context here @OmolaraIdowu, you can actually get the context by calling `binding.root.context`

2023-04-01 07:31 UTC, OmolaraIdowu reviewed
Changes fixed.

2023-04-01 08:24 UTC, segunfrancis requested changes

2023-04-01 08:24 UTC, segunfrancis commented on app/src/main/res/navigation/nav_graph.xml
> +            android:id="@+id/action_homeFragment_to_productDetailsFragment"
@OmolaraIdowu did you see this?

2023-04-01 08:26 UTC, OmolaraIdowu commented on app/src/main/res/navigation/nav_graph.xml
> +            android:id="@+id/action_homeFragment_to_productDetailsFragment"
Oh, I didn’t

2023-04-01 12:19 UTC, segunfrancis approved these changes

2023-04-01 12:20 UTC, merged